### ISSUE TITLE
The Desktop Entry is not working

### ISSUE THREAD

**Issue by Painadath** [gl91306/lunar#1]
You put ~/lunarclient.Appimage but it must be $HOME/lunarclient.Appimage and also it is not working when the tried to laucnh 2.7 the loading screen opened but after a few seconds game crashed why?

**Comment by gl91306** [comment]
could you please attach a video or somthing of that happening cause that never happend to me

**Comment by Painadath** [comment]
Sry after the crash I deleted all the game files so it is hard to test it again and also I used a older version of appimage .but what about desktop entry?

**Comment by gl91306** [comment]
k i chaged the script to make the desktop entry point to $HOME

**Comment by gl91306** [comment]
also can you test if the latest build is working
