### ISSUE TITLE
RP reload crash

### ISSUE THREAD

**Issue by terrified9** [gl91306/lunar#14]
It was working yesterday but now when reloading/changing resource pack it crashes. I have fake kms if it affects something.

[renderer.log](https://github.com/gl91306/lunar/files/6998105/renderer.log)

(Demo)
https://user-images.githubusercontent.com/52547763/129688184-a12ffef1-a97e-4cdd-abaf-5b63a1d871e7.mp4

**Comment by gl91306** [comment]
does /home/pi/lwjgl2arm32/libwebp-imageio32.so exist?

**Comment by gl91306** [comment]
also are you on 64 or 32 bit

**Comment by terrified9** [comment]
> does /home/pi/lwjgl2arm32/libwebp-imageio32.so exist?

nope, that lib is missing. and im using 32 bit

**Comment by terrified9** [comment]
got the lib from this repo; seems that issue is fixed since it now reloads normally

**Comment by KolpixTV** [comment]
same issue but after restarting minecraft the textures are loaded

**Comment by gl91306** [comment]
send screenshot
or video
