### ISSUE TITLE
Java doesnt launch

### ISSUE THREAD

**Issue by terrified9** [gl91306/lunar#17]
**Describe the bug**
u downlaod latest appimage
launch
java doent launch
**Paste contents of /.lunarclient/logs/renderer.log here, after it crashed after you set launcher to stay visible when launched.**
heres short
Lunar Client Launch Error
Short: Java launch fail
Description: Lunar Client has failed to launch. A report has been automatically submitted.
Launcher ID: 53b355aa6f58c7f587a23c3964a97a842eb5bd3e1ddf6c00b6dc5b9000cca1a4
Launcher Version: 2.7.2
OS: linux x64
Game Version: 1.8/master
Launch Type: OFFLINE

render:  https://hastebin.com/emupitagul.csharp

**Comment by oxmc** [comment]
@timof121 We need the full log, please send us all 3 logs.

**Comment by gl91306** [comment]
did you isntall with insntall.sh

**Comment by gl91306** [comment]
or did you just grab the appimage

**Comment by gl91306** [comment]
> @timof121 We need the full log, please send us all 3 logs.

I actually dont. You only need renderer

**Comment by terrified9** [comment]
oh sorry i already fixed it

**Comment by gl91306** [comment]
yay :D
