### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by NoozAbooz** [gl91306/lunar#2]
When launching MC 1.8 I get:

failed to invoke java: error: spawn /home/pi/.lunarclient/jre/zulu8.52.0.23-ca-fx-jre8.0.282-linux_x64/bin/java ENOENT

**Comment by gl91306** [comment]
use the latest version. your using 2.7.0. The 2.7.2 appimage is on the repo

**Comment by NoozAbooz** [comment]
> use the latest version. your using 2.7.0. The 2.7.2 appimage is on the repo

Now I get:
```
Lunar Client Launch Error
Short: Java launch fail
Description: Lunar Client has failed to launch. A report has been automatically submitted.
Launcher ID: 4e3f7199442c3262e9d8c9e8cf0320ae3ec69d7e1b96f1d59550865b67f625c9
Launcher Version: 2.7.2
OS: linux x64
Game Version: 1.8/master
Launch Type: OFFLINE
```

**Comment by gl91306** [comment]
try and paste the logs in .lunarclient/logs: renderer.log and renderer.old.log.

**Comment by NoozAbooz** [comment]
> try and paste the logs in .lunarclient/logs: renderer.log and renderer.old.log.

https://gist.github.com/mobilegmYT/043950bf95e6f22e254e76f3bd723ac0

**Comment by gl91306** [comment]
its kinda hard to talk on github so im dmming u on discord. also, doesn /home/pi/lwjgl2arm32 exist?
