### ISSUE TITLE
(aarch64) Lunar black screen

### ISSUE THREAD

**Issue by terrified9** [gl91306/lunar#20]
**Describe the bug**
Same as #18 , but now this happens on raspbian aarch64
i got all natives and etc but now when i launch the 2.8.0 appimage it just shows a gray screen (doesnt happen with 2.7.3c)
**Paste contents of /.lunarclient/logs/renderer.log here, after it crashed after you set launcher to stay visible when launched.**
no

**Comment by gl91306** [comment]
sorry i must've forgot to add some code, ill re-compile in a bit.

**Comment by gl91306** [comment]
Fixed, please test,
