### ISSUE TITLE
Failed to invoke Java: Error: spawn /opt/jdk/jdk1.8.0_251/jre/bin/java ENOENT raspberry pi 64bit OS

### ISSUE THREAD

**Issue by Virusnest** [gl91306/lunar#22]
Lunar Client Launch Error
Short: Java invoke error
Description: Failed to invoke Java: Error: spawn /opt/jdk/jdk1.8.0_251/jre/bin/java ENOENT
Launcher ID: 00e913c8e84fdfa491c5fc70c8aeef2b0db0b2289bbbad4d862c0eb275990bff
Launcher Version: 2.8.0
OS: linux arm64
Game Version: 1.18/master (NOTE IT DOES THE SAME ON ALL VERSIONS)
Launch Type: OFFLINE

[renderer.log](https://github.com/gl91306/lunar/files/7738210/renderer.log)

**Comment by gl91306** [comment]
did u check 1.8

**Comment by gl91306** [comment]
thats weird cause all versions work for me for the latest realease

**Comment by gl91306** [comment]
did you update? also please note that yu have to selete the old app images when you install.

**Comment by Virusnest** [comment]
I updated and It appears to launch as java is running for a bit before crash. I assume lwjgl2 problem

**Comment by Virusnest** [comment]
I got lwjgl working 1.8.9 launches
i noticed you don't have lwjgl2arm64 in the script so this is my thing:
[LWJGL2ARM64](https://github.com/Virusnest/Aarch64-Natives)

**Comment by gl91306** [comment]
yayy
