### ISSUE TITLE
Don't hardcode the java path

### ISSUE THREAD

**Issue by Botspot** [gl91306/lunar#23]
We at Pi-Apps are transitioning java-installation to use the temurin apt repo for a cleaner installation process without redundant files.
However, with your current Lunar build, this does not work, as it is hardcoded to use `/opt/jdk/jdk-17.0.1+12/bin/java`.

Could this be changed to obey the `$JAVA_HOME` environment variable?

**Comment by gl91306** [comment]
well the original lunar launcher hard codes the java path, and also what would a differnt java path accomplish?

**Comment by gl91306** [comment]
okie the terminmim thing maybe, but i wanna stay true to the lunar launcher, as its ment to be a simpel port to arm rather than having any modifications. Also i never wanted it to be on pi-apps so the terminim thingy isnt really my problem
