### ISSUE TITLE
It wont launch

### ISSUE THREAD

**Issue by 220735540** [gl91306/lunar#24]
I went to launch from the desktop it just showed up white then quit.
then i went to launch it from terminal and it gave me these lines at the end:

(node:1871) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
[1871:0101/090838.875808:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap

**Comment by 220735540** [comment]
Its Rp400 btw :)

**Comment by oxmc** [comment]
@220735540 What version of lunar client is this?

**Comment by 220735540** [comment]
The one in PIKAtchu's Repo

**Comment by 220735540** [comment]
> @220735540 What version of lunar client is this?

lunarclient-2.8.0-armv7l.AppImage

**Comment by gl91306** [comment]
ok so quick fix, run the appimage like this: lunarclient-2.8.0-armv7l.AppImage --no-sandbox

**Comment by gl91306** [comment]
this happend to another person as well, so ill leave this issue open until i fix it permantently

**Comment by 220735540** [comment]
Thanks

**Comment by gl91306** [comment]
i made a permanat fix so this will be closed
