### ISSUE TITLE
Crashes after Microsoft Login

### ISSUE THREAD

**Issue by shioyama** [gl91306/lunar#29]
**Describe the bug**

Launch Minecraft, select single-player mode, microsoft login form comes up, enter details and suddenly music stops and lunar seems stalled, Minecraft never starts.

**Paste contents of /.lunarclient/logs/renderer.log here, after it crashed after you set launcher to stay visible when launched.**

It's too much to paste, but I'm attaching the log. It's actually in `/.lunarclient/logs/launcher/renderer.log`.
[renderer.log](https://github.com/gl91306/lunar/files/7903925/renderer.log)

**Comment by shioyama** [comment]
I've updated to the latest on pi-apps. Now after login the Minecraft music continues playing but I never see Minecraft come up.

I can see a bunch of lunarclient processes running, but the game never starts...

**Comment by gl91306** [comment]
can you tell me your full specs? Like pi version, ram, 32 or 64 bit?

**Comment by gl91306** [comment]
also does /home/pi/lwjgl2arm64/libwebp-imageio64.so exist?

**Comment by gl91306** [comment]
because of inactivity, this issue will be closed. If you wish to re-open it, please do so.

**Comment by shioyama** [comment]
I can't re-open this issue it seems, should I open a new one?

**Comment by shioyama** [comment]
> can you tell me your full specs? Like pi version, ram, 32 or 64 bit?

Raspberry Pi 4 Model B / 8GB.

> also does /home/pi/lwjgl2arm64/libwebp-imageio64.so exist?

Doesn't seem so:

```
stat /home/pi/lwjgl2arm64/libwebp-imageio64.so
stat: cannot statx '/home/pi/lwjgl2arm64/libwebp-imageio64.so': No such file or directory
```

There is no `lwjgl2arm64` directory in `/home/pi`, only `lwjgl2arm32` and `lwjgl3arm32`.

I've successfully run Minecraft on this pi previously with the mojang login, it's only after updating to the microsoft login that things have gone weird.

If it's any help here's what I get from `ps aux | grep lunar`:

```
pi        1166  1.1  1.3 450436 107880 ?       Sl   12:47   0:10 /tmp/.mount_lunarccwTean/lunarclient --no-sandbox
pi        1172  0.3  0.0  11268  1532 ?        Ssl  12:47   0:03 /home/pi/lunarassets/lunarclient.AppImage --no-sandbox
pi        1175  0.0  0.4 158244 36752 ?        S    12:47   0:00 /tmp/.mount_lunarccwTean/lunarclient --type=zygote --no-zygote-sandbox --no-sandbox
pi        1176  0.0  0.4 158244 36876 ?        S    12:47   0:00 /tmp/.mount_lunarccwTean/lunarclient --type=zygote --no-sandbox
pi        1200  3.8  1.3 362264 107780 ?       Sl   12:47   0:32 /tmp/.mount_lunarccwTean/lunarclient --type=gpu-process --field-trial-handle=3444803461364915524,3667054526851942500,131072 --enable-features=WebComponentsV0Enabled --disable-features=CertVerifierService,CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --no-sandbox --gpu-preferences=UAAAAAAAAAAgAAAQAAAAAAAAAAAAAAAAAABgAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAAAA= --shared-files
pi        1206  0.0  0.7 212640 57232 ?        Sl   12:47   0:00 /tmp/.mount_lunarccwTean/lunarclient --type=utility --utility-sub-type=network.mojom.NetworkService --field-trial-handle=3444803461364915524,3667054526851942500,131072 --enable-features=WebComponentsV0Enabled --disable-features=CertVerifierService,CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --lang=ja --service-sandbox-type=network --no-sandbox --shared-files=v8_context_snapshot_data:100
pi        1211  2.7  1.4 415068 118704 ?       Sl   12:47   0:23 /tmp/.mount_lunarccwTean/lunarclient --type=renderer --no-sandbox --field-trial-handle=3444803461364915524,3667054526851942500,131072 --enable-features=WebComponentsV0Enabled --disable-features=CertVerifierService,CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --lang=ja --app-path=/tmp/.mount_lunarccwTean/resources/app.asar --no-sandbox --no-zygote --num-raster-threads=2 --enable-main-frame-before-activation --renderer-client-id=4 --no-v8-untrusted-code-mitigations --shared-files=v8_context_snapshot_data:100
pi        2057 91.5 23.2 2460952 1881944 ?     Ssl  12:50  10:24 /opt/jdk/jdk-17.0.1+12/bin/java --add-modules jdk.naming.dns --add-exports jdk.naming.dns/com.sun.jndi.dns=java.naming -Djna.boot.library.path=natives -Dlog4j2.formatMsgNoLookups=true --add-opens java.base/java.io=ALL-UNNAMED -Xms1024m -Xmx1024m -Djava.library.path=/home/pi/lwjgl2arm32 -Dorg.lwjgl.librarypath=/home/pi/lwjgl2arm32 -Dorg.lwjgl.util.Debug=true -Dorg.lwjgl.util.DebugLoader=true -XX:+DisableAttachMechanism -XX:+UseNUMA -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -XX:+OptimizeStringConcat -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10 -cp vpatcher-prod.jar:lunar-prod-optifine.jar:lunar-libs.jar:lunar-assets-prod-1-optifine.jar:lunar-assets-prod-2-optifine.jar:lunar-assets-prod-3-optifine.jar:OptiFine.jar com.moonsworth.lunar.patcher.LunarMain --version 1.12 --accessToken 0 --assetIndex 1.12 --userProperties {} --gameDir /home/pi/.minecraft --texturesDir /home/pi/.lunarclient/textures --launcherVersion 2.8.0 --width 854 --height 480
```

I can hear the background music playing as I type this. It seems like it's running but somehow the display is not working...

**Comment by shioyama** [comment]
I'm trying the steps you suggested in https://github.com/gl91306/lunar/issues/28, will report back in a bit.

**Comment by shioyama** [comment]
I tried creating the `lwjgl2arm64` directory and putting the files in there as suggested in #28 but nothing changed. Can we re-open this?

**Comment by gl91306** [comment]
ok

**Comment by gl91306** [comment]
does 1.18 work?

**Comment by shioyama** [comment]
Hmm I installed via pi-apps and it seems I'm using 1.12. Is that a problem?

**Comment by gl91306** [comment]
install from the official launcher page. the pi-apps one is rarely updated 🙄

**Comment by shioyama** [comment]
Hmm but I don't really want to have to handle updating separately from pi-apps, that's why I use it. Shouldn't pi-apps be updated? And is 1.12 broken?

**Comment by NoozAbooz** [comment]
> Hmm but I don't really want to have to handle updating separately from pi-apps, that's why I use it. Shouldn't pi-apps be updated? And is 1.12 broken?

Lunar is reccomended on pi-apps because it's friendly to beginners. You could also try the multimc version from pi-apps, although it's a bit harder to use

**Comment by shioyama** [comment]
Ok installed directly from here and I get:

```
./install.sh: line 89:  2248 Segmentation fault      $HOME/lunarclient-2.8.0-armv7l.AppImage
```

Any idea what's going on? :sob:

**Comment by shioyama** [comment]
Ok I got MultiMC5 working, but FWIW I had the exact same issue with Lunar 1.18 (I could loging but then lunar just hangs forever playing the music) after installing it from this repo.

**Comment by gl91306** [comment]
> > can you tell me your full specs? Like pi version, ram, 32 or 64 bit?
> 
> Raspberry Pi 4 Model B / 8GB.
> 
> > also does /home/pi/lwjgl2arm64/libwebp-imageio64.so exist?
> 
> Doesn't seem so:
> 
> ```
> stat /home/pi/lwjgl2arm64/libwebp-imageio64.so
> stat: cannot statx '/home/pi/lwjgl2arm64/libwebp-imageio64.so': No such file or directory
> ```
> 
> There is no `lwjgl2arm64` directory in `/home/pi`, only `lwjgl2arm32` and `lwjgl3arm32`.
> 
> I've successfully run Minecraft on this pi previously with the mojang login, it's only after updating to the microsoft login that things have gone weird.
> 
> If it's any help here's what I get from `ps aux | grep lunar`:
> 
> ```
> pi        1166  1.1  1.3 450436 107880 ?       Sl   12:47   0:10 /tmp/.mount_lunarccwTean/lunarclient --no-sandbox
> pi        1172  0.3  0.0  11268  1532 ?        Ssl  12:47   0:03 /home/pi/lunarassets/lunarclient.AppImage --no-sandbox
> pi        1175  0.0  0.4 158244 36752 ?        S    12:47   0:00 /tmp/.mount_lunarccwTean/lunarclient --type=zygote --no-zygote-sandbox --no-sandbox
> pi        1176  0.0  0.4 158244 36876 ?        S    12:47   0:00 /tmp/.mount_lunarccwTean/lunarclient --type=zygote --no-sandbox
> pi        1200  3.8  1.3 362264 107780 ?       Sl   12:47   0:32 /tmp/.mount_lunarccwTean/lunarclient --type=gpu-process --field-trial-handle=3444803461364915524,3667054526851942500,131072 --enable-features=WebComponentsV0Enabled --disable-features=CertVerifierService,CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --no-sandbox --gpu-preferences=UAAAAAAAAAAgAAAQAAAAAAAAAAAAAAAAAABgAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAAAA= --shared-files
> pi        1206  0.0  0.7 212640 57232 ?        Sl   12:47   0:00 /tmp/.mount_lunarccwTean/lunarclient --type=utility --utility-sub-type=network.mojom.NetworkService --field-trial-handle=3444803461364915524,3667054526851942500,131072 --enable-features=WebComponentsV0Enabled --disable-features=CertVerifierService,CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --lang=ja --service-sandbox-type=network --no-sandbox --shared-files=v8_context_snapshot_data:100
> pi        1211  2.7  1.4 415068 118704 ?       Sl   12:47   0:23 /tmp/.mount_lunarccwTean/lunarclient --type=renderer --no-sandbox --field-trial-handle=3444803461364915524,3667054526851942500,131072 --enable-features=WebComponentsV0Enabled --disable-features=CertVerifierService,CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --lang=ja --app-path=/tmp/.mount_lunarccwTean/resources/app.asar --no-sandbox --no-zygote --num-raster-threads=2 --enable-main-frame-before-activation --renderer-client-id=4 --no-v8-untrusted-code-mitigations --shared-files=v8_context_snapshot_data:100
> pi        2057 91.5 23.2 2460952 1881944 ?     Ssl  12:50  10:24 /opt/jdk/jdk-17.0.1+12/bin/java --add-modules jdk.naming.dns --add-exports jdk.naming.dns/com.sun.jndi.dns=java.naming -Djna.boot.library.path=natives -Dlog4j2.formatMsgNoLookups=true --add-opens java.base/java.io=ALL-UNNAMED -Xms1024m -Xmx1024m -Djava.library.path=/home/pi/lwjgl2arm32 -Dorg.lwjgl.librarypath=/home/pi/lwjgl2arm32 -Dorg.lwjgl.util.Debug=true -Dorg.lwjgl.util.DebugLoader=true -XX:+DisableAttachMechanism -XX:+UseNUMA -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -XX:+OptimizeStringConcat -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10 -cp vpatcher-prod.jar:lunar-prod-optifine.jar:lunar-libs.jar:lunar-assets-prod-1-optifine.jar:lunar-assets-prod-2-optifine.jar:lunar-assets-prod-3-optifine.jar:OptiFine.jar com.moonsworth.lunar.patcher.LunarMain --version 1.12 --accessToken 0 --assetIndex 1.12 --userProperties {} --gameDir /home/pi/.minecraft --texturesDir /home/pi/.lunarclient/textures --launcherVersion 2.8.0 --width 854 --height 480
> ```
> 
> I can hear the background music playing as I type this. It seems like it's running but somehow the display is not working...

you still havent mentioned if ur on a 32 bit os or a 64 bit os

**Comment by shioyama** [comment]
Sorry 32 bit. So I guess that arm64 file wouldn't be expected to work, but anyway the install script ends in a segfault. I can then run lunar and confirm it's 1.18, but I still have the same issue after logging in.

At this point I have MultiMC5 working so I'm happy to close this but it seems odd to me that this isn't working. There's nothing particularly special about this install. :thinking: 

Thanks btw for following me this far down this rabbit hole...

**Comment by gl91306** [comment]
lol thanks for opening the issue in the first place, i hadnt had one on this repo for a while back then.
