### ISSUE TITLE
When trying to login [invalid session ?]

### ISSUE THREAD

**Issue by Rak1ta** [gl91306/lunar#30]
When you try to sign in with Microsoft, a sign-in error occurs. Lunar reports that the account was added successfully, but the red icon on the left shows an {_**invalid session ?**_} That is, I can’t go further than the launcher, because I haven’t logged in.
Raspberry Pi 4B Raspbian Debian 10 32bit
Installed from [Pi-Apps](https://github.com/Botspot/pi-apps/blob/master/apps/Minecraft%20Java/install-32)
![Безымянный](https://user-images.githubusercontent.com/88277343/152843709-120d8094-461f-4492-9fa5-11db24b6ae98.png)
[renderer.log](https://github.com/gl91306/lunar/files/8017543/renderer.log)

**Comment by gl91306** [comment]
has this worked previously?

**Comment by Rak1ta** [comment]
@gl91306 I haven't tried it before, I'm trying now.
Could this be because I didn't purchase the java version of the game on my account? MultiMC5 warned me that I need a java version of the game, but authorization was successful.

**Comment by gl91306** [comment]
of course you need to purchase the java game. the two versions are sperate

**Comment by gl91306** [comment]
wait i misclocked sorry

**Comment by gl91306** [comment]
misclicked*

**Comment by Rak1ta** [comment]
> you need to purchase the java game

Such a login error due to the lack of a game on the account? I will clarify so as not to be mistaken, since I communicate with you through an interpreter.

**Comment by gl91306** [comment]
well minecraft is a video game that costs money. 27 usd to be exact. Lunar launcher isnt a cracked launcher, so if you try to login to the game with an account that hasnt purchased minecraft, it will not work

**Comment by Rak1ta** [comment]
@gl91306 i have minecraft but win10 edition on my account, so I'll clarify why there was an error. Thanks!

**Comment by gl91306** [comment]
ok!

**Comment by gl91306** [comment]
wait i mean ur welcome
