### ISSUE TITLE
bug lunar client mi aiutate 

### ISSUE THREAD

**Issue by richi545** [gl91306/lunar#31]
Lunar Client Launch Error
Short: Unknown error
Description: An unknown error has occurred: FetchError: request to https://launchermeta.mojang.com/v1/packages/f6ad102bcaa53b1a58358f16e376d548d44933ec/1.8.json failed, reason: self signed certificate
Launcher ID: 136db6f97b685ad91b10e44c60fca3b75aca0b0574cd9485690c59b734d4c8b5
Launcher Version: 2.9.4
OS: win32 x64
Game Version: 1.8/master
Launch Type: OFFLINE

**Comment by gl91306** [comment]
try opening https://launchermeta.mojang.com/v1/packages/f6ad102bcaa53b1a58358f16e376d548d44933ec/1.8.json in browser, then click the button with the building next to the url, then click the lock, then take a screenshot of what it says

**Comment by gl91306** [comment]
also whats ur os, bitness(32 or 64), and and you on a rasberry pi?

**Comment by gl91306** [comment]
also i think u speak italian so ill translate this


> prova ad aprire https://launchermeta.mojang.com/v1/packages/f6ad102bcaa53b1a58358f16e376d548d44933ec/1.8.json nel browser, quindi fai clic sul pulsante con l'edificio accanto all'URL, quindi fai clic sul lucchetto, quindi fai uno screenshot di ciò che dice


> anche qual è il tuo sistema operativo, bitness (32 o 64) e tu su un rasberry pi?

> scusa anche se la traduzione non è corretta, ho usato google translate
