### ISSUE TITLE
Sound not working

### ISSUE THREAD

**Issue by 220735540** [gl91306/lunar#33]
The sound on lunar is just not working. Im using a bluetooth speeker and sound isnt just coming through. Ive tried other speakers but it still isnt working

**Comment by gl91306** [comment]
Does sound work for any other apps?

**Comment by 220735540** [comment]
Yes

**Comment by gl91306** [comment]
Does sound work for normal minecraft?

**Comment by gl91306** [comment]
like multimc or smth

**Comment by 220735540** [comment]
Not sure. It works on my brothers lunar though

**Comment by gl91306** [comment]
pase a screenshot of the contents of /home/pi/lwjgl2arm32

**Comment by 220735540** [comment]
Like the files?

**Comment by 220735540** [comment]
![IMG_0210](https://user-images.githubusercontent.com/96502446/159761802-80305f97-5d37-4120-92ad-22147e30d433.jpeg)

**Comment by gl91306** [comment]
well u have all the libs so just tru launching minecraft on multimc. If it doesnt work then its ur pi's issue

**Comment by 220735540** [comment]
I

**Comment by 220735540** [comment]
K

**Comment by gl91306** [comment]
imma close dis cause u have said nothing
