### ISSUE TITLE
Lunar Client Launch Error Short: Failed to download item Description: Failed to download item: getaddrinfo EAI_AGAIN textures.lunarclientcdn.com Launcher ID: 472e7a67664d1458df371a327312a62dc6a210e517cf750c38360598de3e5bc4 Launcher Version: 2.10.1 OS: linux arm64 Game Version: 1.19/master Launch Type: OFFLINELunar Client Launch Error Short: Failed to download item Description: Failed to download item: getaddrinfo EAI_AGAIN textures.lunarclientcdn.com Launcher ID: 472e7a67664d1458df371a327312a62dc6a210e517cf750c38360598de3e5bc4 Launcher Version: 2.10.1 OS: linux arm64 Game Version: 1.19/master Launch Type: OFFLINE

### ISSUE THREAD

**Issue by Pokemo761** [gl91306/lunar#37]
Luna client won't launch on raspberry pi  64 bit OS
Lunar Client Launch Error
Short: Failed to download item
Description: Failed to download item: getaddrinfo EAI_AGAIN textures.lunarclientcdn.com
Launcher ID: 472e7a67664d1458df371a327312a62dc6a210e517cf750c38360598de3e5bc4
Launcher Version: 2.10.1
OS: linux arm64
Game Version: 1.19/master
Launch Type: OFFLINE

**Comment by gl91306** [comment]
this is a wifi issue

**Comment by gl91306** [comment]
try restarting ur wifi and try again

**Comment by gl91306** [comment]
im closing this cause no response
