### ISSUE TITLE
Try Making Badlion

### ISSUE THREAD

**Issue by starlite-developer** [gl91306/lunar#39]
Your project is really great and amazing!

I use a raspberry pi 4 and lunar is good for fps, but after researching I have found that Badlion Client is better for fps on LOW END computers. I tried running this on box64 but it has a launch error and I tried running lunar with box64 and I got the same error. Since lunar and badlion are similar, maybe you can get it to work. I suggest you try to make badlion client just as you have done lunar.

**Comment by gl91306** [comment]
💀 there not even similar and im not a fan of badlion plus ive tried doing it before and badlions source code is more securly packed so yeah also badlion sucks

**Comment by gl91306** [comment]
thx 4 the suggestion tho 👍
