### ISSUE TITLE
Fix release assets

### ISSUE THREAD

**Issue by theofficialgman** [gl91306/lunar#41]
there is no reason for assets to be split below 100MB https://github.com/gl91306/lunar/releases

Github has a git code file size limit of 100MB

Github release assets must be under 2GB https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases#storage-and-bandwidth-quotas

**Comment by gl91306** [comment]
Hey gman, thanks for mentioning this, the reason I split it in the release is that there used to be an error that came up when I was up uploaded the full binaries to the release, so I uploaded the split ones there instead. I have no clue why it works now but not then but I just upaded 👍
