### ISSUE TITLE
Cant open Lunar client on Raspberry pi os bookworm

### ISSUE THREAD

**Issue by G265Dev** [gl91306/lunar#42]
I went to open Lunar client and it gave me a popup message for an error so i tried to reinstall and it still showed the same error
![297903286-261a8cc7-2a76-4a6a-9663-ae9a13a67f34](https://github.com/gl91306/lunar/assets/100205162/db636200-59e4-4111-ba26-8853b0eb18f4)

My system specs:
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 01/16/2024
Latest Pi-Apps version: 01/17/2024
Kernel: aarch64 6.1.0-rpi7-rpi-v8
Device model: Raspberry Pi 4 Model B Rev 1.2
SOC identifier: bcm2711
Cpu name: Cortex-A72
Ram size: 3.79 GB
Raspberry Pi OS image version: 2023-12-05
Language: en_US.UTF-8

**Comment by oxmc** [comment]
@DatBoiG265 What version of lunar are you using?

**Comment by G265Dev** [comment]
> @DatBoiG265 What version of lunar are you using?

I'll let you know in a minute once I have checked

**Comment by G265Dev** [comment]
@oxmc Question how do I check what version of lunar client am I useing?

**Comment by oxmc** [comment]
What did you download? that should have a certain release.

**Comment by G265Dev** [comment]
> What did you download? that should have a certain release.

In the pi-apps files it says in install-64.sh that the version that gets installed is lunarclient-2.10.1-arm64.AppImage

**Comment by oxmc** [comment]
Are you willing to compile lunar from source? it might be just an issue on our end.

**Comment by G265Dev** [comment]
> Are you willing to compile lunar from source? it might be just an issue on our end.

Yes I'll try.
I would need a list of commands to put into terminal so I don't screw it up though.

**Comment by oxmc** [comment]
first install nodejs from pi-apps

you can install it from terminal or from the gui

from terminal: `cd ~/pi-apps/manage 'install' 'Node.JS'` * note my spelling of the name might be incorrect*

**Comment by G265Dev** [comment]
> first install nodejs from pi-apps

Will do

**Comment by G265Dev** [comment]
What the next step?

**Comment by oxmc** [comment]
have you already cloned the repo?

**Comment by oxmc** [comment]
if not, run: `git clone https://github.com/gl91306/lunar`

**Comment by G265Dev** [comment]
cloned the repo now whats next?

**Comment by oxmc** [comment]
cd into the dir, and run `npm i`

**Comment by G265Dev** [comment]
ok will do

**Comment by oxmc** [comment]
oh- i completly forgot- this repo just has the require files not the actual launcher, i apologise, i'll talk to pikachu

**Comment by G265Dev** [comment]
> oh- i completly forgot- this repo just has the require files not the actual launcher, i apologise, i'll talk to pikachu

Okay

**Comment by oxmc** [comment]
@DatBoiG265 Try downloading this version: https://github.com/gl91306/lunar/releases/download/v3.0.3/lunarclient-3.03-arm64.AppImage

**Comment by G265Dev** [comment]
> @DatBoiG265 Try downloading this version: https://github.com/gl91306/lunar/releases/download/v3.0.3/lunarclient-3.03-arm64.AppImage

Will do also are there any apt packages I will have to install to get it running

**Comment by oxmc** [comment]
as far as im aware, no

**Comment by G265Dev** [comment]
> > @DatBoiG265 Try downloading this version: https://github.com/gl91306/lunar/releases/download/v3.0.3/lunarclient-3.03-arm64.AppImage
> 
> Will do also are there any apt packages I will have to install to get it running

Ok

**Comment by G265Dev** [comment]
@oxmc It doesn't seem to support accounts using pc gamepass to play minecraft java

**Comment by G265Dev** [comment]
> @oxmc It doesn't seem to support accounts using pc gamepass to play minecraft java

Because I launch lunar client useing terminal to see what's wrong and its says error unable to get minecraft profile

**Comment by gl91306** [comment]
@DatBoiG265 don't install from pi-apps, they haven't fixed an issue with releases. Install using the install script on this repo, depending on the architecture of your system. Like install32 for 32 bit and 64 for 64.

**Comment by G265Dev** [comment]
> @DatBoiG265 don't install from pi-apps, they haven't fixed an issue with releases. Install using the install script on this repo, depending on the architecture of your system. Like install32 for 32 bit and 64 for 64.

Will do.
Also does Lunar Client have game pass support on raspberry pi?

**Comment by gl91306** [comment]
If your Minecraft account is connected to a game pass, it will work. Also please note that this port is not official so please report an issue in this repo if u have any future problems :)

**Comment by gl91306** [comment]
Clsoing

**Comment by G265Dev** [comment]
Thank you very much this has helped :)

**Comment by DatBoiG265** [comment]
Thank you very much this has helped :)
