### ISSUE TITLE
News

### ISSUE THREAD

**Issue by G265Dev** [gl91306/lunar#44]
Just to let you guys all know, the lunar client has been set as hidden on pi-apps now due to them not fixing their install/uninstall script.

**Comment by gl91306** [comment]
I know, Ill have to implement that through a dumb pull request or something. Ill do it when I have time as I'm in no rush.

**Comment by G265Dev** [comment]
> I know, Ill have to implement that through a dumb pull request or something. Ill do it when I have time as I'm in no rush.

Fair enough 👌🏻
