### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by ghost** [gl91306/lunar#5]
in the menu, i selected accessories, then run lunar client for rpi, here is what it says

Invalid desktop entry file: '/home/pi/.local/share/applications/Lunar-Client.desktop'

also how to run lunar client

**Comment by gl91306** [comment]
try running the install script again

**Comment by ghost** [comment]
ok

**Comment by ghost** [comment]
i did ./lunarclient-2.7.3a-armv7l.AppImage, it showed up lunar client, but had the same error as https://github.com/gl91306/lunar/issues/6
