### ISSUE TITLE
[Feature Request] ARM64 builds

### ISSUE THREAD

**Issue by ryanfortner** [gl91306/lunar#8]
Is Lunar Client able to run on arm64 operating systems?

if so it would be helpful to add the builds, since there are a good handful of users using arm64 OS'es including me.

**Comment by NoozAbooz** [comment]
> Is Lunar Client able to run on arm64 operating systems?
> 
> if so it would be helpful to add the builds, since there are a good handful of users using arm64 OS'es including me.

Pikachu said that their working on arm64 builds right now.

**Comment by gl91306** [comment]
Building for arm64 reqires me to have a 64 bit os, which I dont have. Either when I get a new sd card, or when someone offers to test 64 bit on their pi is when I will start developing arm64

**Comment by NoozAbooz** [comment]
> Building for arm64 reqires me to have a 64 bit os, which I dont have. Either when I get a new sd card, or when someone offers to test 64 bit on their pi is when I will start developing arm64

You can use 64-bit kernel and make a 64-bit container. `sudo apt install raspbian-nspawn-64` will set up everything for you.

**Comment by gl91306** [comment]
I know, Ive done this before, but I dont want to do it again, as last time I did it I had to compile a arm32 libray and that caused errors with my pi confused on weather its 32 or 64. When I uninstalled it, I still had those errors, so thats why I dont trust nspawn-64. So Im going to wait for 

> either when I get a new sd card, or when someone offers to test 64 bit on their pi is when I will start developing arm64

**Comment by NoozAbooz** [comment]
> I know, Ive done this before, but I dont want to do it again, as last time I did it I had to compile a arm32 libray and that caused errors with my pi confused on weather its 32 or 64. When I uninstalled it, I still had those errors, so thats why I dont trust nspawn-64. So Im going to wait for
> 
> > either when I get a new sd card, or when someone offers to test 64 bit on their pi is when I will start developing arm64

Vdesktop also exists 😉

**Comment by gl91306** [comment]
ye, but still there might be some errors If I dont test on an actual arm64 OS.

**Comment by NoozAbooz** [comment]
> ye, but still there might be some errors If I dont test on an actual arm64 OS.

Multiboot? RonR's multiboot lets you install another OS on your sd card without needing reflashing.

**Comment by gl91306** [comment]
Actually now that I think about it electron supports cross platform building. So I think my plan of action would be to make a 64 bit build, build it, and send it to someone with a 64 bit OS

**Comment by gl91306** [comment]
k its done [here](https://github.com/gl91306/lunar/raw/master/install64.sh)
